# Welcome to Jekyll!

#

# This config file is meant for settings that affect your whole blog, values

# which you are expected to set up once and rarely need to edit after that.

# For technical reasons, this file is *NOT* reloaded automatically when you use

# 'jekyll serve'. If you change this file, please restart the server process.



# Site settings

title: Junseok Homepage

email: 21700302@handong.edu

description: OSSLab

baseurl: "" # the subpath of your site, e.g. /blog

url: "https://junduck15.github.io" # the base hostname & protocol for your site


github_username: Junduck15

remote_theme : "mmistakes/minimal-mistakes"

paginate: 5

theme-dark: true #Set to true to change to dark website theme



plugins: [jekyll-paginate, kramdown]



# Build settings

markdown: kramdown
